# Generated by Django 3.2.12 on 2022-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0004_auto_20220425_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='training_day',
            field=models.CharField(max_length=10),
        ),
    ]
