# Generated by Django 3.2.12 on 2022-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0007_auto_20220425_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='Time',
        ),
        migrations.AddField(
            model_name='game',
            name='Ending_hour',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='game',
            name='Starting_hour',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
