# Generated by Django 3.2.12 on 2022-04-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0002_alter_game_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Time',
            field=models.CharField(default='4 p.m. till 6 p.m.', max_length=30),
        ),
    ]
