# Generated by Django 3.2.12 on 2022-04-25 10:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0003_alter_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Ending_hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='Starting_hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='training_day',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='Time',
            field=models.CharField(default='2 p.m. till 3 p.m.', max_length=30),
        ),
    ]
