# Generated by Django 3.2.12 on 2022-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0005_alter_team_training_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='training_day',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
