# Generated by Django 3.2.12 on 2022-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0009_annoucement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='news',
            field=models.TextField(),
        ),
    ]
